### ISSUE TITLE
/speed brakes spectator game mode. Can't move!! 

### ISSUE THREAD

**Issue by DEVBenSon** [carelesshippo/SpectatorModeRewrite#19]
**Describe the bug**
/speed does not work and makes the player not able to move anymore in the mode & yes I've set the permission

**To Reproduce**
1. Give user/group permission "smpspectator.use, smpspectator.speed:"
2. do "/s" 
3. do any type of speed "/speed `number between 1-5`"

**Minecraft version**
1.16.3

**Console error**
Nothing in console 
![image](https://user-images.githubusercontent.com/63822688/98050191-103f2c00-1e29-11eb-99c8-8cf691609ac7.png)
^^ Just this in chat 

**Expected behavior**
Well yea move around in the mode 

**Screenshots**
idk how I would show it in a screenshot

**Additional context**
I've tried reinstalling plugin
I've tried restarting server 
I've tried restarting client side

**Comment by ohowe1** [comment]
Thanks for the report. Is the permission message in the screenshot a part of the bug? Other than that, I have found the issue and am going to push an update soon.

**Comment by DEVBenSon** [comment]
yea carelesshippo it's part of the overall bug! I've seen there is a new update now so thank you for fixing it ;)
