### ISSUE TITLE
Bad Commands

### ISSUE THREAD

**Issue by kevahu** [carelesshippo/SpectatorModeRewrite#21]
Hi,
I have just tried this plugin and when I was setting this up and testing its features. I noticed that the bad commands works, but only for those commands that don't require parameters... For example:
(/msg is in bad commands)
when I do "/msg" it blocks it just fine. But when I do "/msg player hi" it wasn't blocked at all, and I did not even receive the "cannot execute" message.

I used version 1.4.4, on a 1.16.4 papermc server, with only the plugin and PermissionEx.

This is, unfortunately, an important feature if I want to use this plugin on my server.
I can make it possible with some permissions and stuff, but it would be more convenient if it did work.

**Comment by ohowe1** [comment]
Fixed
