### ISSUE TITLE
Don't allow players to use spectator close to a monster

### ISSUE THREAD

**Issue by carlinitos** [carelesshippo/SpectatorModeRewrite#23]
Would be nice to have the plugin check wether a player is close to a monster and if that's the case, fail. That way player's can't escape an imminent fight, and also, aren't in an akward position when teleported back from spectator. Better if this is toggleable thru config

**Comment by ohowe1** [comment]
Hello. I have the coding done but I still have to test that and it is a bit time consuming. Attached is the jar for the update if you want to do some testing yourself and let me know the bugs.
[SpectatorMode-1.4.6.zip](https://github.com/carelesshippo/SpectatorModeRewrite/files/5922305/SpectatorMode-1.4.6.zip)

**Comment by ohowe1** [comment]
Added
