### ISSUE TITLE
Some players unable to use spectator command

### ISSUE THREAD

**Issue by hashalite** [carelesshippo/SpectatorModeRewrite#25]
**Describe the bug**
Most players are able to use the command without issues, but one of my players receives an error whenever they try to enter spectator.  It also sends an error in the console.

**To Reproduce**
Unknown

**Minecraft version**
1.16.5

**Console error**
https://pastebin.com/eWVr1UFh

**Comment by ohowe1** [comment]
Just to clarify, this error is given when the player tries to enter spectator?

**Comment by hashalite** [comment]
Yes.

**Comment by ohowe1** [comment]
In the `data.yml` file is there a section with the UUID of the player that is having problems?

**Comment by hashalite** [comment]
Yes, this is what it looks like:
https://pastebin.com/HMHkRsvY

**Comment by ohowe1** [comment]
Hi. Just remove that section and if it happens again let me know.

**Comment by hashalite** [comment]
Resetting the data file worked, thanks.
