### ISSUE TITLE
Integrate with PaperMC's Anti Xray?

### ISSUE THREAD

**Issue by ghost** [carelesshippo/SpectatorModeRewrite#26]
Is there a way to integrate this with paper's anti x-ray? This could be useful to hide ores while they are in spectator mode so they can't use it to find things. I still want them to be able to use the plugin at any y-level, but it would be neat to hide the ores.

**Comment by ohowe1** [comment]
Hi. I'm not sure about integrating with paper anti-xray, but I could look into disabling ores in spectator. Is that what you are looking for?

**Comment by ghost** [comment]
I didn't even know that you could do that with plugins. That would be great!

**Comment by ohowe1** [comment]
I have looked into it and it is possible, but honestly not really practical. There are other plugins that operate like paper anti x-ray but, like papers, would not be able to integrate with this plugin. As for the possible part, I could develop my own solution for this but it seems like it would introduce some major bugs that could occur and would not be worth it.
