### ISSUE TITLE
You Can Use Leads In Spec

### ISSUE THREAD

**Issue by DoubleZPlaying** [carelesshippo/SpectatorModeRewrite#27]
**Describe the bug**
If I'm holding an animal on a lead and go into spectator mode the animal is somehow still attached. I can fly around with the animal still attached to the lead.

**To Reproduce**
1. Leash an animal
2. Go into chat and run /s
3. Fly around. As long as you aren't too fast the animal will stay connected

**Minecraft version**
1.16.4-1.16.5

**Console error**
No error

**Expected behavior**
Lead comes unattatched

**Comment by ohowe1** [comment]
This is a vanilla behavior but a config value has been added to prevent this (enabled by default). I had no idea about this so thanks for the report.
