### ISSUE TITLE
Issue setting Luck Perms for only certain people to use tool

### ISSUE THREAD

**Issue by Chick3N3** [carelesshippo/SpectatorModeRewrite#31]
**Describe the bug**
We have an issue that allows everyone to use the tool and not just the people with the luck perms roles that have access to the smpspectate.use. We have disabled the tool using the config.yml file so everyone does not have access to it but the luck perms roles still can not use it. 

**Minecraft version**
1.16.1

**Expected behavior**
We would like this plugin to be ONLY accessible to users with a specific luck perms role.

**Comment by ohowe1** [comment]
Hi. The default smpspectator.use value is true so in order to make it so only some people can use it you need to set it to false in the default group of luckperms and then true to those who should be able to. Hope this resolved it and if not reopen this issue or create another one.
