### ISSUE TITLE
Placeholder mob sometimes doesn't disappear

### ISSUE THREAD

**Issue by kevahu** [carelesshippo/SpectatorModeRewrite#34]
In some occasions the placeholder mob does not disappear.
It may have something to do with the placeholder being out of render distance when going back into survival mode.

https://user-images.githubusercontent.com/45965340/114764967-de7daa00-9d64-11eb-8977-fe46e4b8fb1a.mp4

**Comment by ohowe1** [comment]
Hello. I cannot reproduce this bug on my test server. What version of minecraft are you on? Version of spectator Mode? And what server software? And is there any errors or logs in console?

**Comment by kevahu** [comment]
I'm using the latest version of the game (1.16.5) running Yatopia (#77) with Java 15 and the plugin version is 1.4.9
And I don't see any errors in console.

I am going to see if I am able to reproduce the issue on a test server with only the plugin.

**Comment by kevahu** [comment]
I have just tested on my private server with just the plugin.
And it looks fine now, So I guess I have a conflicting plugin or something, nothing to do with your plugin.

Thank you for replying so fast!
