### ISSUE TITLE
Speed still works even when disabled or permission set to false.

### ISSUE THREAD

**Issue by SoraShiunin** [carelesshippo/SpectatorModeRewrite#35]
**Describe the bug**
/speed still works even without permission(Not Op) or if its disabled in config.

**To Reproduce**
Disable or set permission to false for speed. (Same Result)

**Minecraft version**
1.16.5
SMP Spectator Mode - 1.4.9
**Console error**
No errors.

**Expected behavior**
Speed isn't enabled. 

**Screenshots**
![Screenshot_1120](https://user-images.githubusercontent.com/23641964/115094662-44f5fa00-9f16-11eb-842e-683f714ed297.png)

**Additional context**
Same result even if no permission or disabled.

**Comment by ohowe1** [comment]
Thanks for the report. Fixed
