### ISSUE TITLE
Could not pass event ChunkLoadEvent to SpectatorMode v1.5.1

### ISSUE THREAD

**Issue by Uboaaaaa** [carelesshippo/SpectatorModeRewrite#37]
**Describe the bug**
The console was then spammed with dozens of errors until the server froze and shutdown.

**To Reproduce**
Appears to happen when a spectator player teleports away from their own loaded chunk. But happens rather randomly that I cannot consistently reproduce.

**Minecraft version**
1.16.5

**Console error**
https://paste.gg/p/anonymous/8dd5293251bb41309514d42ef086edde

**Expected behavior**
Nothing to happen.

**Additional context**
I acknowledge that you might not be willing to provide support for the server core I'm using (Yatopia). However I was only able to encounter it on this active server with players.
Looking for anyone using Paper/Spigot sharing this issue.

**Comment by ohowe1** [comment]
It is a problem with placeholder mob (even if you do not have it enabled) placeholder mob will be removed in the next version. For now I would recommend a rollback to the previous version.
Edit: i will actually just publish a new version without it

**Comment by ohowe1** [comment]
Should be resolved now
