### ISSUE TITLE
Option to completely disable /speed command

### ISSUE THREAD

**Issue by oskarkk** [carelesshippo/SpectatorModeRewrite#38]
**Is your feature request related to a problem? Please describe.**
Essentials (and many other plugins, I guess) is using the /speed command. This plugin conflicts with it, so that when I use /speed while not in spectator mode, I'm changing my spectator-mode speed, not the speed with which I'm normally walking/flying. You can set an alias in commands.yml like this:

```
  speed:
  - essentials:speed $1-
```

But then the tab completion doesn't work.

**Describe the solution you'd like**
Make an option in the config that would prevent the plugin from registering the `/speed` command. Right now we have "speed" option in the config, but setting that to "false" works in such a way that using `/speed` is still handled by this plugin.

**Comment by ohowe1** [comment]
I’ll add this to the 2.0 feature list.

**Comment by ohowe1** [comment]
Implemented
