### ISSUE TITLE
plugin is not removing persistence from mobs when player leaves spectator

### ISSUE THREAD

**Issue by sxphirus** [carelesshippo/SpectatorModeRewrite#49]
**Describe the bug**
After using /s to deactivate spectator mode persistence is not being removed from entities 

**To Reproduce**
1. Use /s while mobs are around the user
2. Leave /s
3. More mobs will spawn in as persistence has been added and not removed correctly ? 

**Minecraft version**
1.17.1

**Expected behavior**
Persistence is removed

**Additional context**
Possibly adding a config option for adding persistence to mobs or removing the feature altogether
(https://github.com/carelesshippo/SpectatorModeRewrite/blob/b34be58a849992dc06f72d402c2cdfba374c23e6/src/main/java/me/ohowe12/spectatormode/state/State.java#L164)
I understand this is added so /s users can see mobs around them, however, it can cause huge groups of mobs to never despawn, making the plugin not very practical when in use on a public server.

**Comment by ohowe1** [comment]
There is a config option for this currently. It is the `mobs` config value.
