### ISSUE TITLE
Add conduit power to spectators

### ISSUE THREAD

**Issue by jontyms** [carelesshippo/SpectatorModeRewrite#5]
**Is your feature request related to a problem? Please describe.**
No 

**Describe the solution you'd like**
I would like the effect conduit power to be added to spectators and removed when they exit spectator to allow for better visibility in water.
**Describe alternatives you've considered**

**Additional context**

**Comment by carelesshippo** [comment]
Added in version 1.3.8.
Thanks for the feature request
