### ISSUE TITLE
Allow teleport while user is in spectator mode

### ISSUE THREAD

**Issue by etorresh** [carelesshippo/SpectatorModeRewrite#51]
**Feature request**
While the player is in spectator mode allow them to teleport to other players. When the player goes back to survival mode they return to their original position.

**Additional context**
I plan to work on the PR in the next few months but I'll leave the feature request here in case anyone is interested and has more free time than me.

**Comment by ohowe1** [comment]
Hi. This can be done with the hot bar when in vanilla spectator. While in spectator click 1, then 1 again, then select the player you want to teleport with the number keys. For more details, the GUIs section of this page: https://minecraft.fandom.com/wiki/Spectator
