### ISSUE TITLE
Allow server administrators/users to disable chat messages.

### ISSUE THREAD

**Issue by NickPetrone** [carelesshippo/SpectatorModeRewrite#9]
At the moment, it appears that server administrators are unable to disable the messages displayed in chat when changing between spectator and survival. Removing the line for a chat message in the config appears to return it to the default text. Removing the text in the apostrophes results in a blank message appearing. Ideally, there would be either an option for each message to allow for error messages to still appear, or an option to disable non-error messages. Another option on top of that would be implementing it as a command to allow individual players to disable/enable it and potentially add a config line that allows or disallows players to disable it or just include it in permissions.

**Comment by carelesshippo** [comment]
For the option to disable messages, would this only be for the switching to spectator and survival, or all messages except for error messages?

**Comment by NickPetrone** [comment]
Personally, I'd like to just disable the messages for switching between spectator and survival. I wrote the post in a way to keep other users in mind.

**Comment by carelesshippo** [comment]
Added!
